-- Generated by scripts/generate-sqlite-schema.py; do not edit by hand.
-- Cumulative schema equivalent to the PostgreSQL migration chain.

CREATE TABLE account_imports (
    did text NOT NULL,
    source_document jsonb NOT NULL,
    repository_imported boolean DEFAULT FALSE NOT NULL,
    created_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    PRIMARY KEY (did),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE account_passkeys (
    credential_id bytea NOT NULL,
    did text NOT NULL,
    label text NOT NULL,
    public_key_cose bytea NOT NULL,
    signature_count bigint NOT NULL,
    backup_eligible boolean NOT NULL,
    backed_up boolean NOT NULL,
    transports jsonb NOT NULL,
    created_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    last_used_at timestamptz,
    CHECK (((NOT backed_up) OR backup_eligible)),
    CHECK (((length(credential_id) >= 1) AND (length(credential_id) <= 1023))),
    CHECK (((length(label) >= 1) AND (length(label) <= 64))),
    CHECK (((length(public_key_cose) >= 1) AND (length(public_key_cose) <= 4096))),
    CHECK (((signature_count >= 0) AND (signature_count <= '4294967295'))),
    CHECK ((json_type(transports) = 'array')),
    PRIMARY KEY (credential_id),
    FOREIGN KEY (did) REFERENCES account_webauthn_users(did) ON DELETE CASCADE
);
CREATE TABLE account_preferences (
    did text NOT NULL,
    preferences jsonb NOT NULL,
    CHECK (((json_type(preferences) = 'array') AND (json_array_length(preferences) <= 1000))),
    PRIMARY KEY (did),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE account_recovery_codes (
    did text NOT NULL,
    code_hash text NOT NULL,
    CHECK ((length(code_hash) = 43)),
    PRIMARY KEY (did, code_hash),
    FOREIGN KEY (did) REFERENCES account_totp(did) ON DELETE CASCADE
);
CREATE TABLE account_tokens (
    token_hash text NOT NULL,
    did text NOT NULL,
    purpose text NOT NULL,
    email text NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    CHECK ((purpose IN ('confirm-email', 'reset-password', 'delete-account', 'update-email', 'sign-in', 'plc-operation'))),
    PRIMARY KEY (token_hash),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE account_totp (
    did text NOT NULL,
    sealed_secret bytea NOT NULL,
    confirmed boolean DEFAULT FALSE NOT NULL,
    enrollment_epoch bigint NOT NULL,
    enrollment_expires_at timestamptz NOT NULL,
    last_step bigint,
    failed_attempts integer DEFAULT 0 NOT NULL,
    attempt_window timestamptz NOT NULL,
    created_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    CHECK (((failed_attempts >= 0) AND (failed_attempts <= 5))),
    PRIMARY KEY (did),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE account_webauthn_users (
    did text NOT NULL,
    user_handle bytea NOT NULL,
    CHECK ((length(user_handle) = 32)),
    PRIMARY KEY (did),
    UNIQUE (user_handle),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE accounts (
    did text NOT NULL,
    handle text NOT NULL,
    email text,
    password_hash text,
    email_confirmed boolean DEFAULT FALSE NOT NULL,
    status text DEFAULT 'active' NOT NULL,
    created_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    delete_after text,
    email_auth_factor boolean DEFAULT FALSE NOT NULL,
    invites_disabled boolean DEFAULT FALSE NOT NULL,
    invite_note text,
    status_before_takedown text DEFAULT 'active' NOT NULL,
    takedown_ref text,
    imported boolean DEFAULT FALSE NOT NULL,
    oauth_epoch bigint DEFAULT 0 NOT NULL,
    CHECK (((NOT email_auth_factor) OR email_confirmed)),
    CHECK ((oauth_epoch >= 0)),
    CHECK ((status_before_takedown IN ('active', 'deactivated'))),
    CHECK ((status IN ('active', 'deactivated', 'taken_down', 'deleted', 'provisioning'))),
    UNIQUE (email),
    UNIQUE (handle),
    PRIMARY KEY (did)
);
CREATE TABLE app_passwords (
    id uuid NOT NULL,
    did text NOT NULL,
    name text NOT NULL,
    password_digest text NOT NULL,
    privileged boolean DEFAULT FALSE NOT NULL,
    created_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    UNIQUE (did, name),
    UNIQUE (did, password_digest),
    UNIQUE (id, did),
    PRIMARY KEY (id),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE authenticator_recoveries (
    did text NOT NULL,
    previous_version bigint NOT NULL,
    security_version bigint NOT NULL,
    reference text NOT NULL,
    database_role text DEFAULT 'sqlite' NOT NULL,
    removed_factors jsonb NOT NULL,
    completed_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    CHECK ((security_version > previous_version)),
    CHECK ((previous_version >= 0)),
    CHECK (((length(reference) >= 1) AND (length(reference) <= 128))),
    PRIMARY KEY (did, previous_version),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE blob_delete_jobs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    object_bucket text NOT NULL,
    object_key text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    status text DEFAULT 'pending' NOT NULL,
    available_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    last_error text,
    created_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    did text,
    cid text,
    CHECK (((did IS NULL) = (cid IS NULL))),
    CHECK ((status IN ('pending', 'failed'))),
    UNIQUE (object_bucket, object_key)
);
CREATE TABLE blobs (
    did text NOT NULL,
    cid text NOT NULL,
    mime_type text NOT NULL,
    content bytea,
    created_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    size bigint NOT NULL,
    storage_backend text DEFAULT 'postgres' NOT NULL,
    object_key text,
    object_bucket text,
    uploaded_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    takedown_ref text,
    CHECK ((size >= 0)),
    CHECK ((((storage_backend = 'postgres') AND (content IS NOT NULL) AND (size = length(content)) AND (object_key IS NULL) AND (object_bucket IS NULL)) OR ((storage_backend = 's3') AND (content IS NULL) AND (object_key IS NOT NULL) AND (object_bucket IS NOT NULL)))),
    PRIMARY KEY (did, cid),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE browser_sessions (
    token_hash text NOT NULL,
    csrf_nonce text NOT NULL,
    did text,
    account_epoch bigint,
    auth_method text,
    authenticated_at timestamptz,
    passkey_request text,
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    CHECK ((auth_method IN ('password', 'passkey'))),
    CHECK ((expires_at > created_at)),
    CHECK (((did IS NULL) = (account_epoch IS NULL))),
    CHECK (((did IS NULL) = (auth_method IS NULL))),
    CHECK (((authenticated_at IS NULL) OR (did IS NOT NULL))),
    CHECK ((length(csrf_nonce) = 43)),
    CHECK ((length(token_hash) = 43)),
    PRIMARY KEY (token_hash),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE email_outbox (
    id uuid NOT NULL,
    payload jsonb NOT NULL,
    status text DEFAULT 'pending' NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    available_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    lease_token uuid,
    lease_until timestamptz,
    last_error text,
    created_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    sent_at timestamptz,
    CHECK ((status IN ('pending', 'sending', 'sent', 'failed'))),
    PRIMARY KEY (id)
);
CREATE TABLE handle_reservations (
    handle text NOT NULL,
    did text NOT NULL,
    permanent boolean DEFAULT FALSE NOT NULL,
    UNIQUE (handle, did),
    PRIMARY KEY (handle),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE handle_updates (
    did text NOT NULL,
    target_handle text NOT NULL,
    external_handle boolean NOT NULL,
    operation bytea NOT NULL,
    operation_cid text NOT NULL,
    directory_url text NOT NULL,
    status text DEFAULT 'pending' NOT NULL,
    attempts bigint DEFAULT 0 NOT NULL,
    available_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    lease_token uuid,
    lease_until timestamptz,
    last_error text,
    operation_kind text DEFAULT 'handle' NOT NULL,
    next_rotation_key bytea,
    next_rotation_public bytea,
    next_signing_key bytea,
    next_signing_public bytea,
    previous_signing_key text,
    CHECK (((status = 'working') = (lease_token IS NOT NULL))),
    CHECK (((status = 'working') = (lease_until IS NOT NULL))),
    CHECK ((operation_kind IN ('handle', 'submit', 'rotate', 'signing', 'recovery'))),
    CHECK ((((operation_kind = 'rotate') AND (next_rotation_key IS NOT NULL) AND (next_rotation_public IS NOT NULL)) OR ((operation_kind <> 'rotate') AND (next_rotation_key IS NULL) AND (next_rotation_public IS NULL)))),
    CHECK ((((operation_kind = 'signing') AND (next_signing_key IS NOT NULL) AND (next_signing_public IS NOT NULL) AND (previous_signing_key IS NOT NULL)) OR ((operation_kind <> 'signing') AND (next_signing_key IS NULL) AND (next_signing_public IS NULL) AND (previous_signing_key IS NULL)))),
    CHECK ((status IN ('pending', 'working', 'failed'))),
    PRIMARY KEY (did),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE,
    FOREIGN KEY (target_handle, did) REFERENCES handle_reservations(handle, did)
);
CREATE TABLE invite_codes (
    code text NOT NULL,
    available integer NOT NULL,
    disabled boolean DEFAULT FALSE NOT NULL,
    for_account text NOT NULL,
    created_by text DEFAULT 'admin' NOT NULL,
    created_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    CHECK ((available > 0)),
    PRIMARY KEY (code)
);
CREATE TABLE invite_uses (
    code text NOT NULL,
    used_by text NOT NULL,
    used_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    PRIMARY KEY (code, used_by),
    UNIQUE (used_by),
    FOREIGN KEY (code) REFERENCES invite_codes(code),
    FOREIGN KEY (used_by) REFERENCES accounts(did)
);
CREATE TABLE master_key_rotations (
    previous_fingerprint text NOT NULL,
    fingerprint text NOT NULL,
    generation bigint NOT NULL,
    counts jsonb NOT NULL,
    completed_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    CHECK ((length(fingerprint) = 43)),
    CHECK ((generation > 0)),
    CHECK ((length(previous_fingerprint) = 43)),
    UNIQUE (fingerprint),
    UNIQUE (generation),
    PRIMARY KEY (previous_fingerprint)
);
CREATE TABLE master_key_state (
    id boolean DEFAULT TRUE NOT NULL,
    fingerprint text NOT NULL,
    generation bigint DEFAULT 0 NOT NULL,
    updated_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    CHECK ((length(fingerprint) = 43)),
    CHECK ((generation >= 0)),
    CHECK (id),
    PRIMARY KEY (id)
);
CREATE TABLE oauth_client_assertion_uses (
    client_id_hash text NOT NULL,
    jti_hash text NOT NULL,
    expires_at timestamptz NOT NULL,
    CHECK ((length(client_id_hash) = 43)),
    CHECK ((length(jti_hash) = 43)),
    PRIMARY KEY (client_id_hash, jti_hash)
);
CREATE TABLE oauth_codes (
    code_hash text NOT NULL,
    did text NOT NULL,
    account_epoch bigint NOT NULL,
    snapshot jsonb NOT NULL,
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    CHECK ((expires_at > created_at)),
    CHECK ((length(code_hash) = 43)),
    CHECK ((json_type(snapshot) = 'object')),
    PRIMARY KEY (code_hash),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE oauth_dpop_uses (
    jkt text NOT NULL,
    jti_hash text NOT NULL,
    expires_at timestamptz NOT NULL,
    CHECK ((length(jkt) = 43)),
    CHECK ((length(jti_hash) = 43)),
    PRIMARY KEY (jkt, jti_hash)
);
CREATE TABLE oauth_interactions (
    interaction_hash text NOT NULL,
    browser_hash text NOT NULL,
    csrf_nonce text NOT NULL,
    snapshot jsonb NOT NULL,
    did text,
    account_epoch bigint,
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    completed_at timestamptz,
    CHECK ((length(browser_hash) = 43)),
    CHECK ((expires_at > created_at)),
    CHECK (((did IS NULL) = (account_epoch IS NULL))),
    CHECK ((length(csrf_nonce) = 43)),
    CHECK ((length(interaction_hash) = 43)),
    CHECK ((json_type(snapshot) = 'object')),
    PRIMARY KEY (interaction_hash),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE oauth_par_requests (
    request_hash text NOT NULL,
    client_id text NOT NULL,
    parameters jsonb NOT NULL,
    client_binding jsonb NOT NULL,
    dpop_jkt text NOT NULL,
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    permission_sets jsonb DEFAULT '{}' NOT NULL,
    CHECK ((expires_at > created_at)),
    CHECK ((json_type(client_binding) = 'object')),
    CHECK ((length(dpop_jkt) = 43)),
    CHECK ((json_type(parameters) = 'object')),
    CHECK ((json_type(permission_sets) = 'object')),
    CHECK ((length(request_hash) = 43)),
    PRIMARY KEY (request_hash)
);
CREATE TABLE oauth_permission_set_cache (
    nsid text NOT NULL,
    document bytea,
    did text,
    cid text,
    head text,
    rev text,
    fetched_at bigint,
    next_attempt_at bigint NOT NULL,
    lease_id text,
    lease_until bigint NOT NULL,
    CHECK ((((document IS NULL) AND (did IS NULL) AND (cid IS NULL) AND (head IS NULL) AND (rev IS NULL) AND (fetched_at IS NULL)) OR ((document IS NOT NULL) AND (did IS NOT NULL) AND (cid IS NOT NULL) AND (head IS NOT NULL) AND (rev IS NOT NULL) AND (fetched_at IS NOT NULL)))),
    CHECK ((length(document) <= 1000000)),
    CHECK ((length(lease_id) = 43)),
    CHECK (((length(nsid) >= 1) AND (length(nsid) <= 317))),
    PRIMARY KEY (nsid)
);
CREATE TABLE oauth_pkce_uses (
    challenge_hash text NOT NULL,
    expires_at timestamptz NOT NULL,
    CHECK ((length(challenge_hash) = 43)),
    PRIMARY KEY (challenge_hash)
);
CREATE TABLE oauth_sessions (
    session_id text NOT NULL,
    code_hash text NOT NULL,
    did text NOT NULL,
    account_epoch bigint NOT NULL,
    client_id text NOT NULL,
    snapshot jsonb NOT NULL,
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    revoke_reason text,
    CHECK ((expires_at > created_at)),
    CHECK ((length(code_hash) = 43)),
    CHECK ((length(session_id) = 43)),
    CHECK ((json_type(snapshot) = 'object')),
    UNIQUE (code_hash),
    PRIMARY KEY (session_id),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE oauth_tokens (
    token_hash text NOT NULL,
    session_id text NOT NULL,
    kind text NOT NULL,
    scope text NOT NULL,
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    permissions jsonb,
    CHECK ((expires_at > created_at)),
    CHECK (((kind = 'refresh') OR (used_at IS NULL))),
    CHECK (((permissions IS NULL) OR ((kind = 'access') AND (json_type(permissions) = 'array')))),
    CHECK ((kind IN ('access', 'refresh'))),
    CHECK ((length(token_hash) = 43)),
    PRIMARY KEY (token_hash),
    FOREIGN KEY (session_id) REFERENCES oauth_sessions(session_id) ON DELETE CASCADE
);
CREATE TABLE plc_identities (
    did text NOT NULL,
    directory_url text NOT NULL,
    operation bytea NOT NULL,
    operation_cid text NOT NULL,
    rotation_key bytea NOT NULL,
    rotation_public bytea NOT NULL,
    recovery_key text,
    status text DEFAULT 'pending' NOT NULL,
    attempts bigint DEFAULT 0 NOT NULL,
    available_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    lease_token uuid,
    lease_until timestamptz,
    last_error text,
    confirmed_at timestamptz,
    CHECK ((attempts >= 0)),
    CHECK (((status = 'working') = (lease_token IS NOT NULL))),
    CHECK (((status = 'working') = (lease_until IS NOT NULL))),
    CHECK ((status IN ('pending', 'working', 'ready', 'failed', 'prepared'))),
    PRIMARY KEY (did),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE plc_key_rotations (
    did text NOT NULL,
    previous_cid text NOT NULL,
    operation_cid text NOT NULL,
    rotation_public bytea NOT NULL,
    completed_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    PRIMARY KEY (did, previous_cid),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE plc_reconciliations (
    did text NOT NULL,
    local_cid text NOT NULL,
    queued_cid text NOT NULL,
    remote_cid text NOT NULL,
    result jsonb NOT NULL,
    database_role text DEFAULT 'sqlite' NOT NULL,
    completed_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    PRIMARY KEY (did, local_cid, queued_cid, remote_cid),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE plc_recovery_key_changes (
    did text NOT NULL,
    previous_cid text NOT NULL,
    operation_cid text NOT NULL,
    recovery_keys jsonb NOT NULL,
    server_key text NOT NULL,
    completed_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    PRIMARY KEY (did, previous_cid),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE record_blob_refs (
    did text NOT NULL,
    collection text NOT NULL,
    rkey text NOT NULL,
    cid text NOT NULL,
    PRIMARY KEY (did, collection, rkey, cid),
    FOREIGN KEY (did, collection, rkey) REFERENCES records(did, collection, rkey) ON DELETE CASCADE
);
CREATE TABLE records (
    did text NOT NULL,
    collection text NOT NULL,
    rkey text NOT NULL,
    cid text NOT NULL,
    repo_rev text,
    takedown_ref text,
    PRIMARY KEY (did, collection, rkey),
    FOREIGN KEY (cid) REFERENCES repo_blocks(cid),
    FOREIGN KEY (did) REFERENCES repositories(did) ON DELETE CASCADE
);
CREATE TABLE refresh_tokens (
    token_hash text NOT NULL,
    session_id uuid NOT NULL,
    used boolean DEFAULT FALSE NOT NULL,
    expires_at timestamptz NOT NULL,
    PRIMARY KEY (token_hash),
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
);
CREATE TABLE relay_announcements (
    relay_url text NOT NULL,
    hostname text NOT NULL,
    next_attempt_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    lease_id uuid,
    lease_until timestamptz,
    last_success_at timestamptz,
    last_status integer,
    last_error text,
    CHECK (((attempts >= 0) AND (attempts <= 30))),
    CHECK (((lease_id IS NULL) = (lease_until IS NULL))),
    CHECK ((last_error IN ('http-error', 'transport-error'))),
    PRIMARY KEY (relay_url, hostname)
);
CREATE TABLE repo_block_owners (
    did text NOT NULL,
    cid text NOT NULL,
    PRIMARY KEY (did, cid),
    FOREIGN KEY (cid) REFERENCES repo_blocks(cid),
    FOREIGN KEY (did) REFERENCES repositories(did) ON DELETE CASCADE
);
CREATE TABLE repo_blocks (
    cid text NOT NULL,
    content bytea NOT NULL,
    created_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    PRIMARY KEY (cid)
);
CREATE TABLE repo_events (
    seq INTEGER PRIMARY KEY AUTOINCREMENT,
    did text NOT NULL,
    rev text,
    commit_cid text,
    created_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    event_type text DEFAULT 'commit' NOT NULL,
    payload bytea,
    FOREIGN KEY (commit_cid) REFERENCES repo_blocks(cid)
);
CREATE TABLE repositories (
    did text NOT NULL,
    head text,
    rev text,
    signing_key bytea NOT NULL,
    public_key bytea NOT NULL,
    PRIMARY KEY (did),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE,
    FOREIGN KEY (head) REFERENCES repo_blocks(cid)
);
CREATE TABLE reserved_signing_keys (
    key_did text NOT NULL,
    did text,
    signing_key bytea NOT NULL,
    public_key bytea NOT NULL,
    created_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    UNIQUE (did),
    PRIMARY KEY (key_did)
);
CREATE TABLE service_token_uses (
    issuer text NOT NULL,
    nonce_hash text NOT NULL,
    expires_at timestamptz NOT NULL,
    PRIMARY KEY (issuer, nonce_hash)
);
CREATE TABLE sessions (
    id uuid NOT NULL,
    did text NOT NULL,
    revoked boolean DEFAULT FALSE NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    app_password_id uuid,
    PRIMARY KEY (id),
    FOREIGN KEY (app_password_id, did) REFERENCES app_passwords(id, did) ON DELETE CASCADE,
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE signing_key_rotations (
    did text NOT NULL,
    previous_key text NOT NULL,
    signing_public bytea NOT NULL,
    operation_cid text,
    repo_commit text NOT NULL,
    repo_rev text NOT NULL,
    completed_at timestamptz DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')) NOT NULL,
    PRIMARY KEY (did, previous_key),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE TABLE webauthn_challenges (
    challenge_hash text NOT NULL,
    browser_hash text NOT NULL,
    did text NOT NULL,
    account_epoch bigint NOT NULL,
    ceremony text NOT NULL,
    request text NOT NULL,
    label text,
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    CHECK ((length(browser_hash) = 43)),
    CHECK ((ceremony IN ('register', 'authenticate'))),
    CHECK ((length(challenge_hash) = 43)),
    CHECK ((expires_at > created_at)),
    CHECK ((length(request) <= 65536)),
    PRIMARY KEY (challenge_hash),
    FOREIGN KEY (did) REFERENCES accounts(did) ON DELETE CASCADE
);
CREATE INDEX account_passkeys_account ON account_passkeys (did);
CREATE INDEX account_tokens_did_purpose ON account_tokens (did, purpose);
CREATE INDEX blobs_by_upload_time ON blobs (uploaded_at);
CREATE INDEX browser_sessions_expiry ON browser_sessions (expires_at);
CREATE INDEX email_outbox_ready ON email_outbox (available_at) WHERE (status IN ('pending', 'sending'));
CREATE INDEX handle_updates_due ON handle_updates (available_at) WHERE (status = 'pending');
CREATE INDEX handle_updates_lease ON handle_updates (lease_until) WHERE (status = 'working');
CREATE INDEX invite_codes_owner ON invite_codes (for_account);
CREATE INDEX oauth_client_assertion_uses_expiry ON oauth_client_assertion_uses (expires_at);
CREATE INDEX oauth_codes_expiry ON oauth_codes (expires_at);
CREATE INDEX oauth_dpop_uses_expiry ON oauth_dpop_uses (expires_at);
CREATE INDEX oauth_interactions_expiry ON oauth_interactions (expires_at);
CREATE INDEX oauth_par_requests_expiry ON oauth_par_requests (expires_at);
CREATE INDEX oauth_permission_set_cache_eviction ON oauth_permission_set_cache (next_attempt_at);
CREATE INDEX oauth_pkce_uses_expiry ON oauth_pkce_uses (expires_at);
CREATE INDEX oauth_sessions_account ON oauth_sessions (did);
CREATE INDEX oauth_sessions_expiry ON oauth_sessions (expires_at);
CREATE INDEX oauth_sessions_owner_page ON oauth_sessions (did, session_id) WHERE (revoked_at IS NULL);
CREATE INDEX oauth_tokens_expiry ON oauth_tokens (expires_at);
CREATE INDEX oauth_tokens_session ON oauth_tokens (session_id);
CREATE INDEX plc_provision_due ON plc_identities (available_at) WHERE (status = 'pending');
CREATE INDEX plc_provision_lease ON plc_identities (lease_until) WHERE (status = 'working');
CREATE INDEX record_blob_refs_by_cid ON record_blob_refs (did, cid);
CREATE INDEX records_by_collection ON records (collection, did);
CREATE INDEX records_by_revision ON records (did, repo_rev);
CREATE INDEX repo_block_owners_cid ON repo_block_owners (cid);
CREATE INDEX repo_events_did_seq ON repo_events (did, seq);
CREATE INDEX service_token_uses_expiry ON service_token_uses (expires_at);
CREATE INDEX sessions_app_password ON sessions (app_password_id);
CREATE INDEX sessions_did ON sessions (did);
CREATE INDEX webauthn_challenges_account ON webauthn_challenges (did, expires_at) WHERE (used_at IS NULL);
CREATE INDEX webauthn_challenges_expiry ON webauthn_challenges (expires_at);

-- Mirror of the PostgreSQL advance_oauth_epoch trigger: credential/status
-- changes bump the epoch, and the epoch can never decrease. Recursive
-- triggers stay disabled, so the corrective UPDATE does not refire.
CREATE TRIGGER accounts_oauth_epoch AFTER UPDATE ON accounts
FOR EACH ROW
WHEN NEW.oauth_epoch <> MAX(NEW.oauth_epoch,
       OLD.oauth_epoch + (CASE WHEN NEW.password_hash IS NOT OLD.password_hash
                              OR NEW.email IS NOT OLD.email
                              OR NEW.email_confirmed IS NOT OLD.email_confirmed
                              OR NEW.email_auth_factor IS NOT OLD.email_auth_factor
                              OR NEW.status IS NOT OLD.status THEN 1 ELSE 0 END))
BEGIN
  UPDATE accounts SET oauth_epoch = MAX(NEW.oauth_epoch,
       OLD.oauth_epoch + (CASE WHEN NEW.password_hash IS NOT OLD.password_hash
                              OR NEW.email IS NOT OLD.email
                              OR NEW.email_confirmed IS NOT OLD.email_confirmed
                              OR NEW.email_auth_factor IS NOT OLD.email_auth_factor
                              OR NEW.status IS NOT OLD.status THEN 1 ELSE 0 END))
  WHERE did = NEW.did;
END;

