#!/usr/bin/env python3
"""Convert the cumulative PostgreSQL schema into the SQLite baseline migration.

Run `pg_dump --schema-only --no-owner --no-acl` against a freshly migrated
database (scripts/test-postgres.sh style temporary cluster), then:

    python3 scripts/generate-sqlite-schema.py schema.sql \
        > resources/migrations-sqlite/001-baseline.sql

Declared column type names are preserved (timestamptz, boolean, uuid, jsonb,
bytea, ...) because pds.db coerces SQLite values back to PostgreSQL-compatible
Java types using ResultSet metadata. Regex CHECK constraints are weakened to
length checks; application validation remains authoritative.
"""
import re
import sys
from collections import defaultdict

TYPE_MAP = {"timestamp with time zone": "timestamptz", "character varying": "text"}
SERIAL = {("blob_delete_jobs", "id"), ("repo_events", "seq")}
SKIP_TABLES = {"schema_migrations"}
NOW = "strftime('%Y-%m-%d %H:%M:%f','now')"

TRIGGER = """
-- Mirror of the PostgreSQL advance_oauth_epoch trigger: credential/status
-- changes bump the epoch, and the epoch can never decrease. Recursive
-- triggers stay disabled, so the corrective UPDATE does not refire.
CREATE TRIGGER accounts_oauth_epoch AFTER UPDATE ON accounts
FOR EACH ROW
WHEN NEW.oauth_epoch <> MAX(NEW.oauth_epoch,
       OLD.oauth_epoch + (CASE WHEN NEW.password_hash IS NOT OLD.password_hash
                              OR NEW.email IS NOT OLD.email
                              OR NEW.email_confirmed IS NOT OLD.email_confirmed
                              OR NEW.email_auth_factor IS NOT OLD.email_auth_factor
                              OR NEW.status IS NOT OLD.status THEN 1 ELSE 0 END))
BEGIN
  UPDATE accounts SET oauth_epoch = MAX(NEW.oauth_epoch,
       OLD.oauth_epoch + (CASE WHEN NEW.password_hash IS NOT OLD.password_hash
                              OR NEW.email IS NOT OLD.email
                              OR NEW.email_confirmed IS NOT OLD.email_confirmed
                              OR NEW.email_auth_factor IS NOT OLD.email_auth_factor
                              OR NEW.status IS NOT OLD.status THEN 1 ELSE 0 END))
  WHERE did = NEW.did;
END;
"""


def expr(text):
    text = re.sub(r"'((?:[^']|'')*)'::text\b", r"'\1'", text)
    text = re.sub(r"'((?:[^']|'')*)'::jsonb\b", r"'\1'", text)
    text = re.sub(r"::(?:text|bigint|integer|regclass|jsonb)\b", "", text)
    text = re.sub(
        r"= ANY \(ARRAY\[([^\]]+)\]\)", lambda m: "IN (" + m.group(1) + ")", text
    )
    text = text.replace("octet_length(", "length(")
    text = text.replace("jsonb_typeof(", "json_type(")
    text = text.replace("jsonb_array_length(", "json_array_length(")
    text = re.sub(
        r"\(?(\w+) ~ '\^\[[^\]]+\]\{(\d+)\}\$'\)?", r"(length(\1) = \2)", text
    )
    text = text.replace("DEFAULT now()", f"DEFAULT ({NOW})")
    text = text.replace("DEFAULT CURRENT_USER", "DEFAULT 'sqlite'")
    text = text.replace("DEFAULT false", "DEFAULT FALSE")
    text = text.replace("DEFAULT true", "DEFAULT TRUE")
    return text


def column_type(name):
    return TYPE_MAP.get(name, name)


def main(path):
    dump = open(path).read()
    tables, order = {}, []
    for match in re.finditer(
        r"CREATE TABLE public\.(\w+) \(\n(.*?)\n\);", dump, re.S
    ):
        name, body = match.group(1), match.group(2)
        if name in SKIP_TABLES:
            continue
        order.append(name)
        columns, checks = [], []
        for raw in re.split(r",\n(?=    \S)", body):
            line = " ".join(raw.split())
            if line.startswith("CONSTRAINT"):
                checks.append(re.sub(r"^CONSTRAINT \w+ ", "", expr(line)))
                continue
            parts = line.split(" ")
            col = parts[0]
            rest = " ".join(parts[1:])
            for pg, lite in sorted(TYPE_MAP.items(), key=lambda kv: -len(kv[0])):
                if rest.startswith(pg):
                    rest = lite + rest[len(pg):]
                    break
            columns.append((col, expr(rest)))
        tables[name] = {"columns": columns, "checks": checks, "constraints": []}

    for match in re.finditer(
        r"ALTER TABLE ONLY public\.(\w+)\n    ADD CONSTRAINT \w+ (PRIMARY KEY|UNIQUE|FOREIGN KEY) (.*?);",
        dump,
        re.S,
    ):
        name, kind, detail = match.groups()
        if name in SKIP_TABLES:
            continue
        detail = " ".join(detail.split()).replace("public.", "")
        serial = next((c for (t, c) in SERIAL if t == name), None)
        if kind == "PRIMARY KEY" and serial and detail == f"({serial})":
            continue
        tables[name]["constraints"].append(f"{kind} {detail}")

    print("-- Generated by scripts/generate-sqlite-schema.py; do not edit by hand.")
    print("-- Cumulative schema equivalent to the PostgreSQL migration chain.\n")
    for name in order:
        spec = tables[name]
        parts = []
        for col, rest in spec["columns"]:
            if (name, col) in SERIAL:
                parts.append(f"    {col} INTEGER PRIMARY KEY AUTOINCREMENT")
            else:
                parts.append(f"    {col} {rest}")
        parts += [f"    {check}" for check in spec["checks"]]
        parts += [f"    {constraint}" for constraint in spec["constraints"]]
        print(f"CREATE TABLE {name} (")
        print(",\n".join(parts))
        print(");")

    for match in re.finditer(
        r"CREATE (UNIQUE )?INDEX (\w+) ON public\.(\w+) USING btree \((.*?)\)( WHERE .*?)?;",
        dump,
    ):
        unique, index, table, cols, where = match.groups()
        if table in SKIP_TABLES:
            continue
        cols = cols.replace(' COLLATE "C"', "")
        where = expr(where) if where else ""
        print(
            f"CREATE {unique or ''}INDEX {index} ON {table} ({cols}){where};"
        )
    print(TRIGGER)


if __name__ == "__main__":
    main(sys.argv[1])
